name: CI Pipeline_kripa

on:
  push:
    branches: [ "KRIPA" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate Project
        run: echo "All tests passed from Kaipashankar's Branchâœ…"
